### ISSUE TITLE
placement address not detected correctly on Windows

### ISSUE THREAD

**Issue by ooeygui** [microsoft/vscode-dapr#101]
I'm using VSCode on Windows with docker configured with Linux containers.
```
0d5d80c1ec59        daprio/dapr         "./placement"            About a minute ago   Up About a minute   0.0.0.0:6050->50005/tcp   dapr_placement
f328c37d00cd        redis               "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:6379->6379/tcp    dapr_redis
```

I was having problems getting the actor store initialized, turns out I was hitting https://github.com/microsoft/vscode-dapr/issues/98. When I configured the component directory, I now hit this issue:
```
dapr initialized. Status: Running. Init Elapsed 1720.5194000000001ms" app_id=app instance=lamadio-sim scope=dapr.runtime type=log ver=0.9.0
time="2020-07-23T11:12:31.94912-07:00" level=warning msg="error establishing client to placement service: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp [::1]:50005: connectex: No connection could be made because the target machine actively refused it.\"" app_id=app instance=lamadio-sim scope=dapr.runtime.actor type=log ver=0.9.0
```

It looks like this line isn't picking up the fact that I'm running on the Windows side:
https://github.com/microsoft/vscode-dapr/blob/2f4edb3e71788429e6ce7b2cd6abcd5090217b36/src/tasks/daprdCommandTaskProvider.ts#L78

I had to manually specify both:
``` json
            "componentsPath": "components",
            "placementAddress": "localhost:6050"
```

**Comment by philliphoff** [comment]
@ooeygui The placement address issue is likely the same as #82, which has been fixed (but not yet shipped).  I'm trying to carve out time to get to #98 and cut a new release (as a pile of bug fixes have accumulated in the past several months).
