### ISSUE TITLE
while debuging with VS Code extension i am getting error

### ISSUE THREAD

**Issue by sedat-eyuboglu** [microsoft/vscode-dapr#107]
while debuging with VS Code extension i am getting

time="2020-08-25T14:22:23.6736781+03:00" level=warning msg="error establishing client to placement service: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp [::1]:50005: connectex: No connection could be made because the target machine actively refused it.\"" app_id=clientcred instance=xxxxxx scope=dapr.runtime.actor type=log ver=0.10.0

Docker hosts the placement at 6050 So i applied "placementAddress": "localhost:6050" in the tasks.json. After that the message disapered.

**Comment by philliphoff** [comment]
This is likely the same issue as #82, which has been fixed (but not yet released).
