### ISSUE TITLE
The default value of the port is "app" when invoking "Dapr: Scaffold Dapr Tasks" command

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-dapr#109]
**OS:** Win10
**Build Version:** 20200827.4

**Repro Steps:**
1. Open a webapi project in VS Code.
2. F1 -> Dapr: Scaffold Dapr Tasks -> .NET Core Launch (web) -> Enter a Dapr ID for the application (default value is app).
3. Check the default value of the port on which the application listens.

**Expect:**
The default value of the port is "5000".
![image](https://user-images.githubusercontent.com/45614674/91517156-bfd6ba00-e91f-11ea-82e2-1beedf50c1d3.png)

**Actual:**
The default value of the port is "app".
![image](https://user-images.githubusercontent.com/45614674/91517168-c5cc9b00-e91f-11ea-87c9-96d520629560.png)

**More Info:**
1. This issue does not reproduce on the previous released extension build.
2. This issue also reproduces for Node.js project.

**Comment by philliphoff** [comment]
This is due to the newer way the Azure UI wizard caches input for each step [vscode-azuretools#789](https://github.com/microsoft/vscode-azuretools/issues/789). I'm going to see if there's a workaround in the meantime.
