### ISSUE TITLE
There is no validation in the JSON payload input box

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-dapr#112]
**OS:** Win10
**Build Version:** 20200827.4

**Repro Steps:**
1. Open a webapi project in VS Code.
2. F1 -> Dapr: Scaffold Dapr Tasks -> .NET Core Launch (web) -> Enter a Dapr ID 'app' for the application -> Enter the port '5000'.
3. Open the "Controllers/WeatherForecastController.cs" file.
4. Add the following within the class definition:	        
```
[HttpPost]
public ActionResult Post([FromBody] object body)
{
  return new JsonResult(body);
}
```
5. Switch to the debug tab and change the configuration to '.NET Core Launch (web) with Dapr', then F5.
6. F1 -> Dapr: Invoke (POST) Application Method -> Enter 'WeatherForecast' with the application method -> Enter an invalid JSON payload.

**Expect:**
There is an error when inputting the invalid JSON payload.

**Actual:**
There is no validation for the JSON payload input box.
![image](https://user-images.githubusercontent.com/45614674/91543839-66877e80-e951-11ea-98b1-34ea76ddb81b.png)

**More Info:**
There is an error in notification when invoking application method.
![image](https://user-images.githubusercontent.com/45614674/91544286-178e1900-e952-11ea-8cfb-897c923771ed.png)

**Comment by philliphoff** [comment]
@v-ruizh Agreed, while we *do* catch and report the error, it's not at the most convenient point (i.e. during input of the JSON).
