### ISSUE TITLE
The default JSON payload is not empty when invoking Dapr application

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-dapr#113]
**OS:** Win10
**Build Version:** 20200827.4

**Repro Steps:**
1. Open a webapi project in VS Code.
2. F1 -> Dapr: Scaffold Dapr Tasks -> .NET Core Launch (web) -> Enter a Dapr ID 'app' for the application -> Enter the port '5000'.
3. Open the "Controllers/WeatherForecastController.cs" file.
4. Add the following within the class definition:
```
[HttpPost]
public ActionResult Post([FromBody] object body)
{
  return new JsonResult(body);
}
```
5. Switch to the debug tab and change the configuration to '.NET Core Launch (web) with Dapr', then F5.
6. F1 -> Dapr: Invoke (POST) Application Method -> Enter 'WeatherForecast' with the application method.
7. Check the default JSON payload.

**Expect:**
The default JSON payload is empty.
![image](https://user-images.githubusercontent.com/45614674/91544792-d1858500-e952-11ea-93bb-093864908e16.png)

**Actual:**
The default JSON payload is 'WeatherForecast' which is the same as the application method value.
![image](https://user-images.githubusercontent.com/45614674/91545059-2b864a80-e953-11ea-860d-1279be029218.png)

**More Info:**
This issue does not reproduce on the previous released extension build.

**Comment by philliphoff** [comment]
This is the same symptom as #109, now fixed.
