### ISSUE TITLE
The JSON payload is not remembered when invoking Dapr application again

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-dapr#114]
**OS:** Win10
**Build Version:** 20200827.4

**Repro Steps:**
1. Open a webapi project in VS Code.
2. F1 -> Dapr: Scaffold Dapr Tasks -> .NET Core Launch (web) -> Enter a Dapr ID 'app' for the application -> Enter the port '5000'.
3. Open the "Controllers/WeatherForecastController.cs" file.
4. Add the following within the class definition:
```
[HttpPost]
public ActionResult Post([FromBody] object body)
{
  return new JsonResult(body);
}
```
5. Switch to the debug tab and change the configuration to '.NET Core Launch (web) with Dapr', then F5.
6. F1 -> Dapr: Invoke (POST) Application Method -> Enter "WeatherForecast" as the application method -> Enter "{ "number": 42 }" as the JSON payload.
7. F1 -> Dapr: Invoke (POST) Application Method again -> Check the default JSON payload.

**Expect:**
The default JSON payload is remembered with "{ "number": 42 }".
![image](https://user-images.githubusercontent.com/45614674/91545750-09d99300-e954-11ea-8298-cd3ac4b4c15b.png)

**Actual:**
The default JSON payload is 'WeatherForecast', the JSON payload is not remembered.
![image](https://user-images.githubusercontent.com/45614674/91545782-1a8a0900-e954-11ea-99c3-08e6bd3d192b.png)

**More Info:**
This issue does not reproduce on the previous released extension build.

**Comment by philliphoff** [comment]
This is the same symptom as #109, now fixed.
