### ISSUE TITLE
Pop up an error "Request failed with status code 404" when publishing message 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-dapr#117]
**OS:** Windows
**Build Version:** 20200831.7

**Repro Steps:**
1. Create a new .NET Core 3.1 ASP.NET Web API application by "dotnet new webapi --no-https --name netwebapp".
2. Open the application in VS Code --> Select "Dapr: Scaffold Dapr Tasks" from Command Palette --> Select ".NET Core Launch (web)" when asked to select a configuration --> Enter an application ID --> Enter an application port.
3. Debug with ".NET Core Launch (web) with Dapr".
4. Create the file "Controllers/TopicController.cs" file and type the below content.
```
using Microsoft.AspNetCore.Mvc;
		
		namespace netwebapp.Controllers
		{
		    [ApiController]
		    public class TopicController : ControllerBase
		    {
		        [HttpGet("dapr/subscribe")]
		        public string[] GetDaprSubscriptions() {
		            return new[] { "topicA" };
		        }
		
		        [HttpPost("topicA")]
		        public ActionResult HandleTopicA([FromBody] object body) {
		            return this.Ok();
		        }
		    }
		}
```
5. Navigate to the Dapr Explorer --> Right click the application --> Select "Publish Message to Application" --> Enter the topic and a payload.

**Expect:**
Succeed to publish message to application.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/57662131/91799693-2af2fa00-ec5a-11ea-9ac7-14111904a86d.png)

**More Info:**
This issue also reproduces for node.js project.

**Comment by philliphoff** [comment]
@v-xinda Thanks for finding this! The issue is ultimately due to a breaking change in the Dapr publish/subscribe spec; they now require specifying the component name used to perform the publish/subscribe in addition to the topic name (as there may now be multiple components that can perform publish/subscribe operations).  This means both that our test code must change to conform to the new subscription spec, as well as the extension change to use an updated endpoint for publishing messages.

**Comment by v-xinda** [comment]
@philliphoff Hi,
Verified this issue on the build 20200902.2, it still reproduces on Windows OS.

**Comment by philliphoff** [comment]
@v-xinda Are you saying that it reproduces *only* on Windows or was that just the platform you happened to test on?  I don't see the issue on Mac or Windows.  One note, make sure you're using the `0.10.0` version of both `dapr` (e.g. `dapr --version`) and `daprd` (`daprd --version`).  I found that, at some point, a later version of the Windows installer moved `daprd` into a different folder so the older version would get invoked on the path instead.  Also, make sure you're using the latest test code in the test instructions (as the code above no longer works with the latest versions of Dapr).

**Comment by v-xinda** [comment]
Verified this issue on the build 20200903.2, it does not reproduce. So close it.
