### ISSUE TITLE
Pop up an error when invoking (POST) application method with an empty payload

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-dapr#121]
**OS:** All
**Build Version:** 20200902.2

**Repro Steps:**

1. Create a new .NET Web API application by "dotnet new webapi --no-https --name netwebapp".
2. Open the application in VS Code --> Select "Dapr: Scaffold Dapr Tasks" from Command Palette --> Select ".NET Core Launch (web)" when asked to select a configuration --> Enter an application ID --> Enter an application port.
3. Add the following within the class definition:
```
[HttpPost]
	public ActionResult Post([FromBody] object body)
	{
              return new JsonResult(body);
        }
```        
4. Debug with ".NET Core Launch (web) with Dapr".
5. Right click the running application --> Select "Invoke (POST) Application Method" --> Enter "WeatherForecast" --> Enter an **empty** payload.
6. Check the result.

**Expect:**
The method was invoked and succeeded.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/62053665/92088382-5d8a2780-edff-11ea-899a-3a6eff84f8b4.png)

**More Info:**

1. This issue also reproduces for node.js project.
2. This issue doesn't reproduce when publishing message to application with an empty payload.

**Comment by philliphoff** [comment]
It looks like we're not handling empty payloads properly in the case of post/publish, though it happens to work for publish.  I'll create a PR for a fix.  Note, however, that you might still get an error response from the server (400 or 415) if the server expects a valid (i.e. non-null) payload (which ASP.NET does, when using the `[FromBody]` attribute.

**Comment by v-mengwe** [comment]
Got it, thanks for your sharing.
