### ISSUE TITLE
Dapr view will refresh one time every 2 seconds

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-dapr#125]
**OS:** Win10
**Build Version:** 20200916.1

**Repro Steps:**
1. Install Dapr extension in VS Code Insiders.
2. Navigate to Dapr view and check its state.

**Expect:**
It will not always refresh.

**Actual:**
Dapr view will refresh one time every 2 seconds.

**Comment by philliphoff** [comment]
@v-ruizh The Dapr extension *does* perform a simple poll for updated application status every ~2 seconds (for lack of a deterministic means to detect Dapr applications starting/stopping).  Is there a UX or performance concern with this approach?  For the latter, we could add similar logic to what we use in the Docker extension to limit refreshing to only when the tree view is focused/visible.

**Comment by v-ruizh** [comment]
@philliphoff I agree with you to add similar logic to what you use in the Docker extension to limit refreshing. 
Now Dapr update application status every ~2 seconds, it seems to always refresh which is confused if no operation occurs.

**Comment by v-mengwe** [comment]
Verified on the latest build 20210104.3, this issue doesn't reproduce for now, so close it.
