### ISSUE TITLE
Dapr extension fails on macOS Catalina

### ISSUE THREAD

**Issue by neildonkin** [microsoft/vscode-dapr#126]
Issue Type: <b>Bug</b>

I have installed the Dapr extension, but when I try to debug my application I get this error: 

Executing task: daprd-debug <

Executing command: daprd --app-id "dapr-pubsub-demo" --app-port "5000" --components-path "./components" --placement-address "localhost:50005"

**/bin/sh: daprd: command not found**

Extension version: 0.3.0
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|-psn_0_901340|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by philliphoff** [comment]
@neildonkin A couple of starting questions: has [Dapr](https://dapr.io/#download) (both the CLI and the runtime) been installed?  Is `daprd` in the `PATH`?  (Earlier versions of Dapr configured binaries to exist in the path, but more recent versions do not.)

**Comment by neildonkin** [comment]
@philliphoff yes Dapr is running and `daprd` is in the `PATH` variable.  I know this for sure because I had to add it manually because the `PATH` doesn't seem to be updated when Dapr is installed on macOS Catalina.

Everything runs fine on Dapr (and Tye, even) but the VS Code Dapr extension doesn't work for me because `daprd` is installed in the `~/.dapr/bin` folder and _not_ the `/bin/sh` folder, as expected by the extension.

**Comment by philliphoff** [comment]
@neildonkin Strange, I'm also using macOS Catalina as my daily driver, with `daprd` installed to `~/.dapr/bin`, with `/users/<user>/.dapr/bin` in the `PATH` and I'm not seeing this behavior.  Can `daprd` be found in the `PATH` when inside a VS Code terminal window?  The extension isn't looking for `daprd` in any particular location, simply spawning the command in the current workspace directory and relying on the shell to find it.  I've had odd things happen path-wise, though, between `bash` and `zsh` on the same machine, so it's entirely possible that it just "happens" to work on my machine.  That said, we do have independent testing across the platforms before the release which I would expect to have caught such an issue.

In any case, I'm happy to jump on a call to help track this down, if you like, schedules and time zones permitting.

**Comment by neildonkin** [comment]
@philliphoff Very strange.  I just tried again this morning and it works.  I haven't changed anything, so I don't know why it's magically just started to work.

I'll keep an eye on it and get back to you if it happens again.

Thanks for your help.

**Comment by philliphoff** [comment]
Great to hear!  I'll close the issue for now, but file again if that or any other issue crops up again.

**Comment by tonysneed** [comment]
I am getting this issue with macOS Big Sur. When I debug a project using the Dapr VS Code extension, I get the following error:

```
> Executing task: daprd-debug <
> Executing command: daprd --app-id "publisher" --components-path "/Users/anthonysneed/.dapr/components" --placement-host-address "localhost:50005" <
/bin/sh: daprd: command not found
```

I noticed that `daprd` was not on my path, so I added the following to **.zshrc**:

```
export PATH=$PATH:/$HOME/.dapr/bin
```

After adding this, I can run `daprd` commands from the Terminal. But the VS Code extension still produces the above error when debugging.

**Comment by philliphoff** [comment]
@tonysneed I recently setup a new M1 machine with Big Sur and added `<user>/.dapr/bin` to my `PATH` in the `.zprofile` file, which seems to work as expected.  I don't claim to know what the differences are between `.zshrc` and `.zprofile`; sometimes it's all just a big mystery to me. :-). In any case, I've filed #139 to allow users to take out some of that mystery when needed.

**Comment by tonysneed** [comment]
Thanks @philliphoff - that worked!  Looking forward to the demystification. 😄
