### ISSUE TITLE
There is an error "Request failed with status code 500“ when publishing message to application

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-dapr#135]
**OS:** Win10
**Build Version:** 20210104.3

**Repro Steps:**

1. Create a new .NET Core 3.1 ASP.NET Web API application by "dotnet new webapi --no-https --name netwebapp".
2. Open the application in VS Code -> Select "Dapr: Scaffold Dapr Tasks" from Command Palette -> Select ".NET Core Launch (web)" when asked to select a configuration -> Enter an application ID -> Enter an application port.
3. Create the file "Controllers/TopicController.cs" file and type the below content.
  ```
  using Microsoft.AspNetCore.Mvc;
		
  namespace netwebapp.Controllers
  {
	  [ApiController]
	  public class TopicController : ControllerBase
	  {
		  [HttpGet("dapr/subscribe")]
		  public ActionResult GetDaprSubscriptions() {
			  return this.Content(@"[{ ""pubsubname"": ""messagebus"", ""topic"": ""topicA"", 
  ""route"": ""topicA"" }]", "application/json");
		  }
				
		  [HttpPost("topicA")]
		  public ActionResult HandleTopicA([FromBody] object body) {
		      return this.Ok();
		  }
	  }
  }
  ```
4. Debug with ".NET Core Launch (web) with Dapr".
5. Navigate to the Dapr Explorer -> Right click the application -> Select "Publish Message to Application" -> Enter the publish with "messagebus” -> Enter the topic with "TopicA" -> Enter a payload with {“number":42}.
6. Check whether publish message to application successfully.

**Expect:**
Succeed to publish message to application.

**Actual:**
Fail to publish message to application with an error.
![image](https://user-images.githubusercontent.com/62053665/103619888-7a7d6580-4f6d-11eb-8f44-c1bc0fddfe24.png)

**More Info:**
This issue also reproduces for Node.js project.
The dapr version and daprd version:

> C:\Users\AzureTest\Desktop\web\netwebapp>daprd --version
> 0.11.3
> C:\Users\AzureTest\Desktop\web\netwebapp>dapr --version
> CLI version: 0.11.0   
> Runtime version: 0.11.3

**Comment by philliphoff** [comment]
@v-mengwe Thanks for catching this; newer versions of the Dapr CLI made changes to the names of the default components such that the test code/procedures no longer work.  I've updated the test code/procedures to match, as well as added instructions to install the 1.0.0 RC versions of the Dapr CLI and runtime (which are now required for the latest builds of the extension).

**Comment by v-mengwe** [comment]
@philliphoff Thanks for your sharing. This issue doesn't reproduce with the updated code/procedures, so close it.
