### ISSUE TITLE
sync daprd task config args with daprd cli args

### ISSUE THREAD

**Issue by databasedav** [microsoft/vscode-dapr#136]
CLI version: 1.0.0-rc.3 
Runtime version: 1.0.0-rc.2
Extension version: 0.3.0

upgrading to runtime 1.0.0-rc.2 and running a vscode dapr extension `daprd` task results in e.g.
```
> Executing command: daprd --app-id "auth" --components-path "./components" --dapr-grpc-port "50006" --dapr-http-port "3503" --log-level "debug" --metrics-port "9095" --placement-address "localhost:50005" --protocol "grpc" <

flag provided but not defined: -placement-address
```

`--placement-address` has changed to `--placement-host-address` and `--protocol` has changed to `--app-protocol` (others might have changed as well) and block using this extension with the latest version of dapr

**Comment by philliphoff** [comment]
@databasedav Yes, 0.3.0 still targets earlier versions of Dapr and so will not necessarily work with the latest 1.0.0 RC releases.  The extension has already been "fixed" (see #129), but we're not currently planning a release until immediately after Dapr 1.0.0 is generally available.

That said, you're free to use a nightly build of the extension until then, for example:

https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/29566/artifacts?artifactName=vsix&api-version=6.0&%24format=zip

> The link will download a `.zip` file that contains a `.vsix` version of the extension that you can manually install.

Please let me know if that doesn't work for you.

**Comment by databasedav** [comment]
@philliphoff the nightly build works for me thanks!

**Comment by vzdesic** [comment]
For me instalation from the nightly build is not working. Here is the error from the log file:

Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: Input string was not in a correct format.

**Comment by philliphoff** [comment]
@vzdesic Which (and what version of) OS and VS Code are you using, and with which build of the Dapr extension?

**Comment by vzdesic** [comment]
@philliphoff 

Windows 10
*************
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
System Type:               x64-based PC

VS Code
*********
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Current DAPR Extension
*************************
v0.3.0 - 03 September 2020

**Comment by philliphoff** [comment]
@vzdesic How odd. I've virtually the same setup (only difference is build 19042 of Win10, which I'd think is immaterial) but have no trouble installing the latest nightly build:

https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/29566/artifacts?artifactName=vsix&api-version=6.0&%24format=zip

**Comment by philliphoff** [comment]
@vzdesic Ah, ok, I can repro it if I attempt to install it by double-clicking the VSIX, which is because `.vsix` file extension is linked to the Visual Studio extension installation component, which expects an altogether different VSIX manifest.  It's easy to see how that could happen.

To install an extension via `.vsix` file in VS Code, you use the "Install from VSIX..." command in the command palette, or in the extended menu of the Extensions tab.

**Comment by vzdesic** [comment]
@philliphoff 

Woow! That is it! **Great great thanks**! Now it works.
