### ISSUE TITLE
Couchbase state store / transactional 

### ISSUE THREAD

**Issue by HazDeploy** [microsoft/vscode-dapr#143]
Issue Type: <b>Feature Request</b>

HI 
Currently couchbase transactional state store is not supported by Dapr. It's an adoption blocker

Extension version: 0.4.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 17.7.0

**Comment by philliphoff** [comment]
@HazDeploy Is this more about the Dapr platform itself or an issue with use of the state store with the VS Code extension in particular?

**Comment by HazDeploy** [comment]
Apparently it’s the dapr component support not supporting couchbase transactional (only CRUD)

**Comment by philliphoff** [comment]
Closing as it appears to be a Dapr component issue and not extension related.
