### ISSUE TITLE
Dapr extension in VS Code only show one of the two running apps

### ISSUE THREAD

**Issue by MonkeyTennis** [microsoft/vscode-dapr#144]
I have set up 2 ASP.NET Core web apis and have configured them both to be called via Dapr. They work fine in isolation.

I have followed the guide to add a compound launch configuration in VS Code:

```
"compounds": [
    {
    "name": "netcoreapp 1 and 2 w/Dapr",
    "configurations": [
        ".NET Core Launch (web) with Dapr",
        ".NET Core Launch (web2) with Dapr"
    ]
    }
]
```
and indeed two debug sessions are started:

![image](https://user-images.githubusercontent.com/1092060/110012605-9ce6f180-7d18-11eb-92d6-23f75e03238c.png)

However, in the Dapr extensions pane, only one app is shown and it seems fairly random as to which one:

![image](https://user-images.githubusercontent.com/1092060/110012508-7e80f600-7d18-11eb-9bef-a06c2174955c.png)

Also, there is a brief moment where both applications are shown whilst the multiple debug sessions are initialised.

Is this a known issue or am I doing something wrong?

**Comment by philliphoff** [comment]
@MonkeyTennis It's not something I've seen, but it's always possible that you've found a bug.  I'll see if it reproduces for me, too.

What version of the extension and Dapr are you using, and on what OS?

**Comment by philliphoff** [comment]
@MonkeyTennis I suspect that you're running into a race condition where each `daprd` instance is trying to use the same ports for its metrics/GRPC/HTTP endpoints, and the last one started is failing.

Neither the extension nor `daprd` will automatically choose free ports during startup; they'll both happily attempt to use the defaults.  (That's something the extension might be able to help with; I'll file an issue for that.) When orchestrating several Dapr-enabled applications in VS Code, you'll need to be more explicit about the ports used by each.

For example, below is the `tasks.json` from the workspace I created to reproduce your issue.  You'll notice that I've explicitly set the `grpcPort`, `httpPort`, and `metricsPort` properties for each `daprd` task to unique values.

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build-web",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/web/web.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "build-web2",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/web2/web2.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "appId": "app",
            "appPort": 5000,
            "grpcPort": 50001,
            "httpPort": 3500,
            "metricsPort": 9090,
            "label": "daprd-debug",
            "type": "daprd",
            "dependsOn": "build-web"
        },
        {
            "appId": "app",
            "label": "daprd-down",
            "type": "daprd-down"
        },
        {
            "appId": "app2",
            "appPort": 5001,
            "grpcPort": 50002,
            "httpPort": 3501,
            "metricsPort": 9091,
            "label": "daprd-debug-1",
            "type": "daprd",
            "dependsOn": "build-web2"
        },
        {
            "appId": "app2",
            "label": "daprd-down-1",
            "type": "daprd-down"
        }
    ]
}
```

**Comment by philliphoff** [comment]
Added #146 to track automatically choosing ports.

**Comment by philliphoff** [comment]
Closing in favor of #146.
