### ISSUE TITLE
flag provided but not defined: -app-id

### ISSUE THREAD

**Issue by tnsholding** [microsoft/vscode-dapr#147]
Trying out the extension (v.0,4.0) with a C# app based on the worker service template (dotnet new worker). Target framework net5.0.

I can successfully start app manually using dapr command, i.e.:
` dapr run --app-id myApp -- dotnet run --dapr-http-port 3500`

But trying to start a debug session in VSCode results in the following error:
```
> Executing task: daprd-debug <
> Executing command: daprd --app-id "myApp" --app-port "5000" --components-path "C:\Users\tnspr\.dapr\components" --placement-host-address "localhost:6050" <
flag provided but not defined: -app-id
```
I ran the task "Dapr: Scaffold Dapr Tasks" to create standard entries in launch.json and tasks.json. 

Am I doing something wrong in setting up debugging in VSCode or is there an issue attaching to a worker service?

**Comment by philliphoff** [comment]
@tnsholding What version of `dapr` CLI/runtime are you using?  What happens when you try to run that same command line (listed after `Executing command:`) on an actual terminal?

**Comment by tnsholding** [comment]
Running version 1.0.1 (both CLI and runtime).

When running the command in the terminal, I get the same error as inside VSCode.

**Comment by philliphoff** [comment]
@tnsholding That's really strange.  If you run `daprd --app-id "myApp"` in a normal terminal window (i.e. not in VS Code), what happens?  (This *should* be the minimal command required to start Dapr.). Are you running VS Code locally, or using a Dev Container, WSL, or SSH to connect to a remote "machine"?

**Comment by tnsholding** [comment]
Sorry for the late reply...
When I run `daprd --app-id "myApp"` in a terminal window, I get the same error: 
`flag provided but not defined: -app-id`

But noticed that running `daprd --version` gives 
`0.1.0 `

while `dapr --version` gives:
```
CLI version: 1.0.1
Runtime version: 1.0.1
```

Is daprd not updated correctly?

**Comment by philliphoff** [comment]
@tnsholding Ah, I think I might know what's happening.  Early on, the Dapr runtime installation would add `daprd` to the `PATH` (which is where the VS Code tooling expects it).  Later, the installer *stopped* adding it to the `PATH` (which required you to add it yourself if using the VS Code tooling).  I bet you have multiple versions of `daprd` installed, an earlier (and outdated) version that's in the `PATH` and `1.0.1`, which is not.

There was a feature (#139) recently implemented which allows you to be explicit about where the VS Code tooling expects binaries (if not in the `PATH`).  I don't know when it'll be released, but you are free to use the CI builds in the meantime.

**Comment by tnsholding** [comment]
Yes - that was exactly it. Thanks!
Very old installation of Dapr was added in the PATH. Once removed, I can now debug in VSCode with daprd.
