### ISSUE TITLE
No web page is opened after debugging the .NET core project 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-dapr#151]
**OS:** Win10
**Build Version:** 20210325.7
**Dotnet Version:** 3.1.407

**Repro Steps:**
1. Create a new .NET Core Web API application and open it in VS Code.
2. F1 -> Dapr: Scaffold Dapr Tasks -> .NET Core Launch (web) -> Enter a Dapr ID 'app' for the application -> Enter the port '5000'.
3. Switch to the debug tab and change the configuration to '.NET Core Launch (web) with Dapr', then F5.
4. Check whether open a web page or not. 

**Expect:**
Open a web page after debugging the project.

**Actual:**
No web page is opened after debugging the project.

**Comment by philliphoff** [comment]
@v-xinda I'm not able to repro this with a .NET Core 5.0 WebAPI project, and see the browser open both when using the "standard" ASP.NET debug launch configuration as well as the Dapr debug launch configuration.  Do see the browser open in one but not the other?  Is this specific to .NET Core 3.1 vs 5.0?

**Comment by v-xinda** [comment]
@philliphoff Verified this issue on the latest build 20210408.1, it doesn't reproduce with  .NET Core 3.1 or 5.0.

**Comment by philliphoff** [comment]
@v-xinda If the issue doesn't reproduce with the latest build, can we call the issue closed?

**Comment by v-xinda** [comment]
@philliphoff I got it. This issue doesn't reproduce with the latest build, so I close it.
