### ISSUE TITLE
Expose more metadata in the Explorer about the services that make up the application

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-dapr#161]

**Comment by jasonviviano** [comment]
## Description
Add a panel to the extension Explorer that displays a Dapr applications metadata.

### Metadata Wanted

•	Dapr HTTP Port 
•	Dapr gRPC Port 
•	Age 
•	Command 
•	App Port

**Comment by philliphoff** [comment]
Closing; enhancements to the current state will be tracked as separate items.
