### ISSUE TITLE
[Feature Request] Expose more configurations in Task.Json

### ISSUE THREAD

**Issue by jasonviviano** [microsoft/vscode-dapr#187]
# Description

## Background
Currently the extension "Scaffold Dapr Tasks' creates a task.json that contains the following line of code at the most basic level.

`{
	"version": "2.0.0",
	"tasks": [
		{
			"appId": "nodeapp",
			"appPort": 3000,
			"label": "daprd-debug",
			"type": "daprd"
			},
		{
			"appId": "nodeapp",
			"label": "daprd-down",
			"type": "daprd-down"
		}
	]
}`

## Request
Expose more of the configurational options as to increase beginner awareness, by creating commented outlines of parameters that are deemed important. Parameters such as:

- componentsPath
- httpPort
- grpcPort

**Comment by philliphoff** [comment]
There's been a back and forth about this in the past, with VS Code preferring simplified configuration files that don't scaffold  default values.  In keeping with that approach, I'm going to "won't fix" this for now.
