### ISSUE TITLE
There is no application in the webpage when opening the debugged project dapr dashboard

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-dapr#194]
**OS:** All
**Build Version:** 20210806.3
**Regression:** Not a Regression

**Repro Steps:**

1. Create a new .NET Core Web API application and open it in VS Code.
2. F1 -> Dapr: Scaffold Dapr Tasks -> .NET Core Launch (web) -> Enter a Dapr ID 'app' for the application -> Enter the port '5000'.
3. Switch to the debug tab and change the configuration to '.NET Core Launch (web) with Dapr', then F5.
4. Navigate to Dapr view -> Click "Open Dapr Dashboard" button -> Open a webpage in the browser.
5. Check whether the  debugged application shows in the webpage.

**Expect:**
The  debugged application shows in the webpage.

**Actual:**
There is no application in the webpage.
![image](https://user-images.githubusercontent.com/62053665/128685914-5f37e158-8c19-462e-9c94-54ef315cd6ec.png)

**More Info:**
This issue also reproduces for Node.js project.

**Comment by philliphoff** [comment]
Currently, the Dapr CLI doesn't recognize applications started directly via `daprd` rather than `dapr`.  As we currently scaffold the debug tasks to use `daprd`, this means that the dashboard won't show that running application.  We have a task to move to scaffolding `dapr` based configurations (#74) and there are outstanding issues on the Dapr CLI to better detect both `dapr` and `daprd` started applications, either of which would resolve this apparent inconsistency.

**Comment by bcraun** [comment]
I'm having a similar issue with the extension where any launched Dapr app is not showing up in the "APPLICATIONS" pane. I followed the short video on the Dapr docs [page](https://docs.dapr.io/developing-applications/ides/vscode/vscode-dapr-extension/) (Dapr Community Call 9) to configure the extension, but am not able to get any Dapr app to show up when launched from the extension.

- macOS Big Sur
- Dapr 1.5.0
- Dapr VSCode extension 0.6.0 Preview

I'd love to be able to use the extension, but this behavior is not expected.

**Comment by philliphoff** [comment]
@bcraun Do you configure VS Code or the workspace to use an explicit path to `daprd`?  I can repro your issue if I do that.  (Typically I would add `daprd` to `PATH`, where I don't see that issue.). You might also try changing the `daprd` task to type `dapr`, as `dapr` should be in the `PATH` already.  (This should also allow your application to show up in the `dapr list` list.)

**Comment by bcraun** [comment]
@philliphoff here's my tasks.json and I'm not (intentionally) setting an explicit path to `daprd`. What can I check to confirm?:

```
{
    "appId": "app3",
    "appPort": 5000,
    "label": "daprd-debug",
    "type": "daprd",
    "dependsOn": "build"
},
{
    "appId": "app3",
    "label": "daprd-down",
    "type": "daprd-down"
}
```

The `dapr`/`daprd` executables are in my path, but for some reason, the `home/bcraun/.dapr/bin` path appears twice?:

`/home/bcraun/.dapr/bin:/Users/bcraun/.dotnet/tools:/home/bcraun/.dapr/bin`

I changed the type to `dapr`, and `app3` does appear in `dapr list` now, but, unfortunately, it doesn't resolve the issue of no applications appearing in the extension.

```
{
    "appId": "app3",
    "appPort": 5000,
    "label": "daprd-debug",
    "type": "dapr",
    "dependsOn": "build"
},
{
    "appId": "app3",
    "label": "daprd-down",
    "type": "daprd-down"
}
```

**Comment by philliphoff** [comment]
> @bcraun What can I check to confirm?

You could check looking in the user/workspace settings (Preferences::Settings::Dapr::Paths::Daprd Path), for example:

```json
{
    "dapr.paths.daprdPath": "~/.dapr/bin/daprd"
}
```

**Comment by bcraun** [comment]
@philliphoff aha! Not sure why, but the paths are explicitly configured for some reason?

![image](https://user-images.githubusercontent.com/641584/151426248-09cedf10-177c-4823-8f7c-b6d5827d3c9f.png)

Removing them resolves the issue!  Just for my understanding, do you know why this behavior happens?

Thanks for the help!

**Comment by philliphoff** [comment]
@bcraun I'm sure it's just a bug when parsing the list of running processes (looking for Dapr instances); we're probably not matching explicit paths properly (assuming most have added `daprd` to `PATH`).

**Comment by bcraun** [comment]
@philliphoff makes sense. Thanks again for the help.

**Comment by bcraun** [comment]
@philliphoff what odd is that if I change the type back to `daprd`, I can execute it from both the VS Code terminal and iTerm, but not when using F5 to debug. It's like the environment isn't getting propagated correctly.

![image](https://user-images.githubusercontent.com/641584/151429665-a0f7c2c1-07e6-4f4a-b1b9-d97e8cd7b418.png)

Executing `daprd` from iTerm2 works, though.

**Comment by bcraun** [comment]
@philliphoff adding the `~/.dapr/bin` path in `~/.profile` and sourcing it resolves the issue, but I only get 404 errors when I try to invoke a `GET` on the sample `GetWeatherForecast` API. It's doubtful these are related so although I can use an F5 workflow to run the app, debugging isn't working. Any thoughts?

**Comment by philliphoff** [comment]
@bcraun Yes, there are a number of unsolved mysteries around setting Mac `PATH`. Not everybody runs into them, and the solutions seem to differ from machine to machine.  :-)

For debugging, what ports are you trying to use, and are you running Monterey?

**Comment by bcraun** [comment]
Big Sur 11.6.2

![image](https://user-images.githubusercontent.com/641584/151439481-f1663353-3b4b-404b-b9b3-ccb26935b96e.png)

**Comment by philliphoff** [comment]
@bcraun Ok, on Monterey port 5000 starts getting used by the system by default to support AirPlay, which often interferes with .NET applications.

You *should* be able to use the CLI to invoke method; if you're using the default ASP.NET WebAPI project template, the method would be `WeatherForecast`, though, no?

**Comment by bcraun** [comment]
@philliphoff yes, totally. A copy/paste error!

**Comment by v-xinda** [comment]
Verified this issue on the latest build 20230324.2, it doesn't reproduce. So close it.
![image](https://user-images.githubusercontent.com/57662131/230573203-9da1abb0-e8d1-45a5-8b8a-aeadd556d411.png)
