### ISSUE TITLE
[Feature Request] Pubsub Component: Watch topics

### ISSUE THREAD

**Issue by jcdickinson** [microsoft/vscode-dapr#196]
As one possible option for double-clicking (or as a menu option) on the pubsub component, how about adding a "watch" feature that logs (somewhere) some topics. This could be really useful for debugging anything that uses pubsub.

**Comment by philliphoff** [comment]
Having the ability to visualize messages published/received is definately something I'd like to see; it's just a matter of getting to it as well as ensuring the Dapr runtime provides the ability to get at that information.
