### ISSUE TITLE
Is this Extension working with Dapr on Kubernetes

### ISSUE THREAD

**Issue by ajaysingh77** [microsoft/vscode-dapr#197]
Today I trying this extension, but it is showing no Application. Currently, I have a distributed-calculator-app installed on Kubernetes locally on Docker-Desktop with WSL2 
The extension is showing "No Dapr applications are running"

![image](https://user-images.githubusercontent.com/18524884/128971849-de6244ad-c2b6-41d3-a703-c66ea37f9e1d.png)
![image](https://user-images.githubusercontent.com/18524884/128971915-24a0d463-3275-405a-8498-6576dea67b1d.png)

Not sure whether I am missing any configuration or this extension is not working with Dapr on Kubernetes

**Comment by philliphoff** [comment]
At the moment the extension provides visualization of local Dapr applications, not those running in a Kubernetes cluster (whether locally or remote).  That said, it's something we've thought about.  I'm going to close this, but keep #198 open as tracking that ask.
