### ISSUE TITLE
A compatible version of dapr runtime has not been found

### ISSUE THREAD

**Issue by feguiguren** [microsoft/vscode-dapr#207]
Hi Folks, my vs code is not picking up Dapr binaries

VS Code Version: 1.62.0
MacOs BigSur 11.6

Running Dapr from VS code terminal produces these outputs:

`$ dapr --version                                                                                                                                                    [8:58:31]
CLI version: 1.4.0 
Runtime version: n/a
 
franciscoe@MacBook franciscoe: ~/dev/git/ccai/conversation-processor
$ where dapr                                                                                                                                                        [8:58:33]
/usr/local/bin/dapr`

Path to Dapr matches the extension configuration

What to do next?

**Comment by philliphoff** [comment]
@feguiguren The extension expects that the Dapr runtime has been installed in addition to the Dapr CLI itself, which is a separate step in [the Dapr setup](https://docs.dapr.io/getting-started/install-dapr-selfhost/).  Can you try doing the following in a terminal, then restarting VS Code:

```bash
$ dapr init
```

**Comment by philliphoff** [comment]
Closing; reopen if the issue continues.
