### ISSUE TITLE
There is no message "dapr initialized. Status: Running" in the terminal window "daprd-debug" after debugging a .NET 6 Web API project with dapr configuration

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-dapr#213]
**OS:** Win10
**Build Version:** 20211202.11
**.NET Version:** 6.0.101
**Regression:** Not a Regression

**Repro Steps:**
1. Create a new .NET 6.0 ASP.NET Web API application by "dotnet new webapi --no-https --name netwebapp".
2. Open the application in VS Code -> Select "Dapr: Scaffold Dapr Tasks" from Command Palette -> Select ".NET Core Launch (web)" when asked to select a configuration -> Enter an application ID (Select the default "app") -> Enter an application port (Select the default "5000").
3. Debug with configuration ".NET Core Launch (web) with Dapr".
4. Check whether there is a message "dapr initialized. Status: Running" in the terminal window "daprd-debug" or not.

**Expect:**
There is a message "dapr initialized. Status: Running" in the terminal window "daprd-debug".

**Actual:**
There is no message "dapr initialized. Status: Running" in the terminal window "daprd-debug".
![image](https://user-images.githubusercontent.com/45614674/146159072-31153b7d-cc11-4742-beb2-cb9af8aefe7b.png)

**More Info:**
1. This issue also reproduces on the previous released dapr extension.
2. This issue does not reproduce for Node.js project.
3. This issue does not reproduce for .NET 5 Web API project.
4. The dapr application is running after debugging the .NET 6 Web API project.

**Comment by philliphoff** [comment]
This is another symptom if the underlying issue attributed to #214.
