### ISSUE TITLE
Fail to invoke the application method for a .NET 6 Web API project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-dapr#214]
**OS:** Win10
**Build Version:** 20211202.11
**.NET Version:** 6.0.101
**Regression:** Not a Regression

**Repro Steps:**
1. Create a new .NET 6.0 ASP.NET Web API application by "dotnet new webapi --no-https --name netwebapp".
2. Open the application in VS Code -> Select "Dapr: Scaffold Dapr Tasks" from Command Palette -> Select ".NET Core Launch (web)" when asked to select a configuration -> Enter an application ID (Select the default "app") -> Enter an application port (Select the default "5000").
3. Debug with configuration ".NET Core Launch (web) with Dapr".
4. F1 -> Dapr: Invoke (GET) Application Method -> Select a Dapr application "app" -> Enter the application method "WeatherForecast" to invoke.
5. Check whether the method is invoked or not.

**Expect:**
The method is invoked without any error.

**Actual:**
Fail to invoke the application method with an error "Request failed with status code 500".
![image](https://user-images.githubusercontent.com/45614674/146160399-581776c6-dbe2-4724-a1b1-ca56585d0ce6.png)

**More Info:**
1. This issue also reproduces on the previous released dapr extension.
2. This issue does not reproduce for Node.js project.
3. This issue does not reproduce for .NET 5 Web API project.

**Comment by v-ruizh** [comment]
This issue also reproduces on the latest dapr extension 20220108.1, it can be reproduced for both "Invoke (GET) Application Method" and "Invoke (POST) Application Method" actions. 
It does not reproduce for "Publish Message to Application" action.

**Comment by philliphoff** [comment]
@v-ruizh The issue appears to be a change in the .NET 6 ASP.NET templates where they now select a random startup port rather than `5000`.  Since this is likely something all will run into, we should look at trying to sniff the selected port out of the `launchSettings.json`.
