### ISSUE TITLE
There is no end process for the "daprd-down" task after stopping debugging

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-dapr#243]
**OS:** All
**Build Version:** 20220629.2
**VS Code Version:** 1.69.0

**Repro Steps:**
1. Create a new .NET 6.0 ASP.NET Web API application by "dotnet new webapi --no-https --name netwebapp".
2. Open the application in VS Code -> Select "Dapr: Scaffold Dapr Tasks" from Command Palette -> Select ".NET Core Launch (web)" when asked to select a configuration -> Enter an application ID (Select the default "app") -> Enter an application port (Select the default one).
3. Debug with configuration ".NET Core Launch (web) with Dapr".
4. Stop debugging and check the terminal window.
5. Check whether there is an end process for the "daprd-down" task in the terminal window.

**Expect:**
There is an end process for the "daprd-down" task in the terminal window, such as the below screen.
![image](https://user-images.githubusercontent.com/45614674/177938654-09ae3b2e-a241-4172-a6ce-4d90d1da8354.png)

**Actual:**
The "daprd-down" task keeps "Shutting down..." status.
![image](https://user-images.githubusercontent.com/45614674/177938530-84bc7e2d-2c4e-4b6a-a840-1904b9a43995.png)

**More Info:**
This issue does not reproduce on VS Code 1.67.2.

**Comment by philliphoff** [comment]
@v-ruizh I think this is just expected behavior now of the VS Code terminal window.  New terminal windows are opened for each instance of the task, so they're *not* actually being reused.
