### ISSUE TITLE
Miss property "version" of tasks.json for Node.js project

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-dapr#47]
**OS:** Windows
**Build Version:** [20200228.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15512&view=results)
**Node.js Version**: 12.x.x

**Repro Steps:**
1. Create and initialize a new Express.js application by below:
> npx express-generator nodeapp
> cd nodeapp
> npm install
2. Open this application folder in VS Code --> Switch to the debug tab -->Select "create a launch.json" file --> Select "Node.js" when asked to select an environment.
3. Select "Dapr: Scaffold Dapr Tasks" from Command Palette --> Select "Launch Program" when asked to select a configuration --> Enter an application ID --> Enter an application port.
4. Open the ".vscode/tasks.json" file.

**Expect:**
There is no any warning/error after opening the tasks.json.

**Actual:**
Miss property "version" of tasks.json.
![image](https://user-images.githubusercontent.com/34729092/75655611-171cfb80-5c17-11ea-9ac4-a8233fdfcd62.png)

.

**Comment by philliphoff** [comment]
@v-dantch Thanks for being so observant! We use a VS Code API to add the tasks (i.e. we don't scaffold the `tasks.json` directly), so this would appear to be an issue with VS Code itself.  I've filed [microsoft/vscode#91911](https://github.com/microsoft/vscode/issues/91911) for that.
