### ISSUE TITLE
There is no a dependency named "dependsOn" for Express.js application

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-dapr#48]
**OS:** Windows
**Build Version:** [20200228.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15512&view=results)
**Node.js Version**: 12.x.x
![image](https://user-images.githubusercontent.com/34729092/75657365-e2ab3e80-5c1a-11ea-992c-41aee2a5f8f9.png)

**Repro Steps:**
1. Create and initialize a new Express.js application by below:
> npx express-generator nodeapp
> cd nodeapp
> npm install
2. Open this application folder in VS Code --> Switch to the debug tab -->Select "create a launch.json" file --> Select "Node.js" when asked to select an environment.
3. Select "Dapr: Scaffold Dapr Tasks" from Command Palette --> Select "Launch Program" when asked to select a configuration --> Enter an application ID --> Enter an application port.
4. Open the ".vscode/tasks.json" file --> Check whether there is a dependency ("dependsOn") and it should set to "build".

**Expect:**
There is a dependency ("dependsOn") and it has been set to "build".

**Actual:**
There is no a dependency named "dependsOn".
![image](https://user-images.githubusercontent.com/34729092/75659034-2bb0c200-5c1e-11ea-92a3-81c182748f70.png)

**Comment by philliphoff** [comment]
@v-dantch You're right, that's a test case bug. The task in the Node.js scenario should *not* have a `"dependsOn"` property as there's no build step for that kind of Node.js application (as the JavaScript is interpreted and not compiled).  I've updated the test case.

**Comment by v-dantch** [comment]
Hi @philliphoff , thanks a lot for your share and help.
