### ISSUE TITLE
Pop up an error when invoking(Get) Application Method with error "Request failed with status code 404"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-dapr#49]
**OS:** Windows
**Build Version:** [20200228.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15512&view=results)
**Node.js Version**: 12.x.x

**Repro Steps:**
1. Create a new .NET Core 3.1 ASP.NET Web API application by "dotnet new webapi --no-https --name netwebapp".
2. Open the application in VS Code --> Select "Dapr: Scaffold Dapr Tasks" from Command Palette --> Select ".NET Core Launch (web)" when asked to select a configuration --> Enter an application ID --> Enter an application port.
3. Debug with ".NET Core Launch (web) with Dapr".
4. Navigate to the Dapr Explorer --> Right click the application --> Select "Invoke (Get) Application Method" --> Enter the application method "users".

**Expect:**
Succeed to invoke the application method.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/75667024-c06dec80-5c2b-11ea-9937-a13bbb92bd50.png)

**More Info:**
This error also reproduces for node.js project.

**Comment by philliphoff** [comment]
@v-dantch For the .NET Core scenario, the method name to invoke is `"WeatherForecast"`, and for Node.js it's `"users"`.  When using those methods for those scenarios, I don't see that error.  Let me know if you see the same. In any case, I'll update the test cases to make the input more prominent.

**Comment by v-dantch** [comment]
Got it. Thanks for your help and share.
