### ISSUE TITLE
When debugging with the extension "dapr list" does not show list of running instances

### ISSUE THREAD

**Issue by msfussell** [microsoft/vscode-dapr#56]
Presumably this is because you run daprd.exe with parameters and app is not launched with "dapr run" command which is what dapr list requires. It would be good to see if we can find a way to make dapr list work int this debugging scenario.

**Comment by philliphoff** [comment]
@msfussell You're correct, `dapr` only tracks applications started via `dapr` and not started via `daprd` directly.  There's an outstanding issue for that: [dapr/cli#220](https://github.com/dapr/cli/issues/220).  There've been recent changes made to the CLI that *should* allow the extension to switch to `dapr` for most scenarios, which would seemingly make that issue moot (though it should still be addressed).

There's also a larger issue in that `dapr` (in standalone mode) will only list applications running on the local machine, and not those running on the local network, which impacts the multiple-dev-containers-on-a-common-Docker-network scenario.  I've filed an issue to start addressing that: [dapr/dapr#1186](https://github.com/dapr/dapr/issues/1186).

**Comment by philliphoff** [comment]
Closing for now; we'll add tasks in response to any CLI changes that enables us to use `dapr` directly and/or allows us a better way to enumerate Dapr applications.

**Comment by tillig** [comment]
Looks like there's a PR for this in the Dapr repo that's been sitting for about six months. The lack of running apps in the list was really confusing.
