### ISSUE TITLE
Allow killing Dapr applications

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-dapr#81]
Add an option to kill a running Dapr application (i.e. its `dapr` or `daprd` instance) from the Dapr applications tree view.  If the application does not shut down nominally after debugging, it's not always obvious how/where to stop it so that the user can restart without fear of strange conflicts.  (Especially since the `dapr` CLI does not show arbitrarily started `daprd` instances.)

The applications tree view could offer a "kill" context menu command (at least for instances that it, itself, started) to allow for quick, forced shutdowns and restarts.

**Comment by jasonviviano** [comment]
# Description

## Background
Currently there is no way to kill a Dapr application detected from the UI found in the VS Code extension. Users would have to either kill the debugging process started that has initiated the Dapr application or kill the application from what ever terminal it has been started.

## Request
Add a command that kills a specific Dapr application when that application is selected. This command should be a right click command option that only effects the selected Dapr application.

## Mockup
![Screen Shot 2021-06-21 at 1 46 32 PM](https://user-images.githubusercontent.com/83607984/122805455-1d653a00-d297-11eb-82d7-4ce6c5ffa94c.png)
