### ISSUE TITLE
dapr scaffold dapr tasks not working in workspace view

### ISSUE THREAD

**Issue by databasedav** [microsoft/vscode-dapr#88]
The command `Dapr: Scaffold Dapr Tasks` produces the error `Open a folder or workspace with a debug launch configuration.` in vscode's workspace view (after doing a `Open Workspace...`). The command works as expected in the folder view (after doing a `Open Folder...`) with the same folders that are in the workspace.

This is on vscode 1.44.2 with the 0.2.1 extension.

**Comment by philliphoff** [comment]
@databasedav Thanks for the report!  VS Code has some quirks with the use of tasks within a workspace that we may not be accommodating as well as we could or should.  We'll take a look!

**Comment by philliphoff** [comment]
We'll need to do the same thing the [`vscode-docker`](https://github.com/Microsoft/vscode-docker) extension does and only scaffold folder-scoped tasks (even when a workspace is open).
