### ISSUE TITLE
dapr cil flag and extentions option names are not match now. (0.8.0 cli)

### ISSUE THREAD

**Issue by mrchypark** [microsoft/vscode-dapr#99]
dapr cli 0.8.0 use -dapr-id flag not --app-id anymore. 

edit/
I misunderstand issue.

I add screenshot below.

**Comment by mrchypark** [comment]
![image](https://user-images.githubusercontent.com/6179259/87629419-f987a300-c76d-11ea-8dae-af4c18032467.png)

**Comment by philliphoff** [comment]
@mrchypark What version of the Dapr CLI and runtime are you using (`dapr --version` and `daprd --version`)?  As far as I know, both 0.8.0 and 0.9.0 (released today) continue to use `--app-id`.  It is possible that might have changed during some intermediate build of 0.8.0.

**Comment by philliphoff** [comment]
Closing this due to lack of a response; if the issue persists, please re-open or otherwise create a new issue.
